import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, LogOut, Plus, Trash2, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { money } from "@/lib/nexo";
export const Route=createFileRoute("/app-transacoes")({component:Transactions});
type Tx={id:string;description:string;amount:number;kind:"income"|"expense";transaction_date:string;notes:string|null};
type Account={id:string;name:string};
type Category={id:string;name:string;kind:"income"|"expense"};
function Transactions(){const nav=useNavigate();const [rows,setRows]=useState<Tx[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [kind,setKind]=useState<"income"|"expense">("expense");const [description,setDescription]=useState("");const [amount,setAmount]=useState("");const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [accountId,setAccountId]=useState("");const [categoryId,setCategoryId]=useState("");
async function load(){const {data:user}=await supabase.auth.getUser();if(!user.user){await nav({to:"/login"});return;}const [t,a,c]=await Promise.all([supabase.from("transactions").select("id,description,amount,kind,transaction_date,notes").eq("user_id",user.user.id).order("transaction_date",{ascending:false}),supabase.from("accounts").select("id,name").eq("user_id",user.user.id).eq("is_active",true),supabase.from("categories").select("id,name,kind").eq("user_id",user.user.id)]);setRows((t.data??[]) as Tx[]);setAccounts((a.data??[]) as Account[]);setCategories((c.data??[]) as Category[]);if(a.data?.[0])setAccountId(a.data[0].id);}
useEffect(()=>{load()},[nav]);
async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");const {data:user}=await supabase.auth.getUser();if(!user.user){setError("Sessão expirada.");setBusy(false);return;}const r=await supabase.from("transactions").insert({user_id:user.user.id,account_id:accountId||null,category_id:categoryId||null,description:description.trim()||"Sem descrição",amount:Number(amount),kind,status:"confirmed",transaction_date:date}).select().single();setBusy(false);if(r.error){setError("Não foi possível salvar. Verifique se existe uma conta cadastrada.");return;}setRows(prev=>[r.data as Tx,...prev]);setOpen(false);setDescription("");setAmount("");}
async function remove(id:string){if(!confirm("Excluir esta transação?"))return;await supabase.from("transactions").delete().eq("id",id);setRows(prev=>prev.filter(x=>x.id!==id));}
async function logout(){await supabase.auth.signOut();await nav({to:"/login"});}
return <main className="nexo-module"><header className="module-header"><a className="icon-button" href="/app"><ArrowLeft size={18}/></a><div><span className="eyebrow">NEXO FINANCE</span><h1>Transações</h1></div><button className="icon-button" onClick={logout}><LogOut size={17}/></button></header><section className="module-hero compact-hero"><span className="eyebrow">MOVIMENTAÇÕES</span><h2>Seu dinheiro, registrado.</h2><p>Adicione receitas e despesas para que o NEXO consiga calcular seu fluxo financeiro real.</p><button className="nexo-button gold" onClick={()=>setOpen(true)}><Plus size={16}/> Nova transação</button></section><section className="module-card"><div className="list-header"><span className="eyebrow">HISTÓRICO</span><strong>{rows.length} registros</strong></div>{rows.length===0?<div className="empty-module"><h3>Nenhuma transação ainda.</h3><p>Comece registrando sua primeira receita ou despesa.</p><button className="nexo-button gold" onClick={()=>setOpen(true)}>Adicionar primeira transação</button></div>:<div className="transaction-list">{rows.map(r=><div className="transaction-row" key={r.id}><div><strong>{r.description}</strong><small>{new Date(r.transaction_date+"T12:00:00").toLocaleDateString("pt-BR")}</small></div><b className={r.kind==="income"?"positive":"negative"}>{r.kind==="income"?"+":"-"} {money(Math.abs(Number(r.amount)))}</b><button className="delete-button" onClick={()=>remove(r.id)}><Trash2 size={15}/></button></div>)}</div>}</section>{open&&<div className="nexo-modal"><form className="modal-card" onSubmit={save}><div className="modal-head"><h3>Nova transação</h3><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div>{error&&<div className="nexo-alert">{error}</div>}<div className="type-toggle"><button type="button" className={kind==="expense"?"selected":""} onClick={()=>setKind("expense")}>Despesa</button><button type="button" className={kind==="income"?"selected":""} onClick={()=>setKind("income")}>Receita</button></div><label>Descrição<input required value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: Supermercado"/></label><label>Valor<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00"/></label><label>Data<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Conta<select required value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Selecione</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Categoria<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Sem categoria</option>{categories.filter(c=>c.kind===kind).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="nexo-button gold full" disabled={busy}>{busy?"Salvando...":"Salvar transação"}</button></form></div>}</main>}
