/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppAssinaturaRouteImport } from './routes/app-assinatura'
import { Route as AppChecklistsRouteImport } from './routes/app-checklists'
import { Route as AppConfiguracoesRouteImport } from './routes/app-configuracoes'
import { Route as AppContasRouteImport } from './routes/app-contas'
import { Route as AppDividasRouteImport } from './routes/app-dividas'
import { Route as AppInsightsRouteImport } from './routes/app-insights'
import { Route as AppMetasRouteImport } from './routes/app-metas'
import { Route as AppPatrimonioRouteImport } from './routes/app-patrimonio'
import { Route as AppPlanejamentoRouteImport } from './routes/app-planejamento'
import { Route as AppRelatoriosRouteImport } from './routes/app-relatorios'
import { Route as AppTransacoesRouteImport } from './routes/app-transacoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/app-assinatura',
  path: '/app-assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChecklistsRoute = AppChecklistsRouteImport.update({
  id: '/app-checklists',
  path: '/app-checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/app-configuracoes',
  path: '/app-configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContasRoute = AppContasRouteImport.update({
  id: '/app-contas',
  path: '/app-contas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDividasRoute = AppDividasRouteImport.update({
  id: '/app-dividas',
  path: '/app-dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/app-insights',
  path: '/app-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/app-metas',
  path: '/app-metas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPatrimonioRoute = AppPatrimonioRouteImport.update({
  id: '/app-patrimonio',
  path: '/app-patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlanejamentoRoute = AppPlanejamentoRouteImport.update({
  id: '/app-planejamento',
  path: '/app-planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/app-relatorios',
  path: '/app-relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/app-transacoes',
  path: '/app-transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/app-assinatura': typeof AppAssinaturaRoute
  '/app-checklists': typeof AppChecklistsRoute
  '/app-configuracoes': typeof AppConfiguracoesRoute
  '/app-contas': typeof AppContasRoute
  '/app-dividas': typeof AppDividasRoute
  '/app-insights': typeof AppInsightsRoute
  '/app-metas': typeof AppMetasRoute
  '/app-patrimonio': typeof AppPatrimonioRoute
  '/app-planejamento': typeof AppPlanejamentoRoute
  '/app-relatorios': typeof AppRelatoriosRoute
  '/app-transacoes': typeof AppTransacoesRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/app-assinatura': typeof AppAssinaturaRoute
  '/app-checklists': typeof AppChecklistsRoute
  '/app-configuracoes': typeof AppConfiguracoesRoute
  '/app-contas': typeof AppContasRoute
  '/app-dividas': typeof AppDividasRoute
  '/app-insights': typeof AppInsightsRoute
  '/app-metas': typeof AppMetasRoute
  '/app-patrimonio': typeof AppPatrimonioRoute
  '/app-planejamento': typeof AppPlanejamentoRoute
  '/app-relatorios': typeof AppRelatoriosRoute
  '/app-transacoes': typeof AppTransacoesRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/app-assinatura': typeof AppAssinaturaRoute
  '/app-checklists': typeof AppChecklistsRoute
  '/app-configuracoes': typeof AppConfiguracoesRoute
  '/app-contas': typeof AppContasRoute
  '/app-dividas': typeof AppDividasRoute
  '/app-insights': typeof AppInsightsRoute
  '/app-metas': typeof AppMetasRoute
  '/app-patrimonio': typeof AppPatrimonioRoute
  '/app-planejamento': typeof AppPlanejamentoRoute
  '/app-relatorios': typeof AppRelatoriosRoute
  '/app-transacoes': typeof AppTransacoesRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app-assinatura'
    | '/app-checklists'
    | '/app-configuracoes'
    | '/app-contas'
    | '/app-dividas'
    | '/app-insights'
    | '/app-metas'
    | '/app-patrimonio'
    | '/app-planejamento'
    | '/app-relatorios'
    | '/app-transacoes'
    | '/cadastro'
    | '/login'
    | '/nova-senha'
    | '/onboarding'
    | '/precos'
    | '/recuperar-senha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app-assinatura'
    | '/app-checklists'
    | '/app-configuracoes'
    | '/app-contas'
    | '/app-dividas'
    | '/app-insights'
    | '/app-metas'
    | '/app-patrimonio'
    | '/app-planejamento'
    | '/app-relatorios'
    | '/app-transacoes'
    | '/cadastro'
    | '/login'
    | '/nova-senha'
    | '/onboarding'
    | '/precos'
    | '/recuperar-senha'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app-assinatura'
    | '/app-checklists'
    | '/app-configuracoes'
    | '/app-contas'
    | '/app-dividas'
    | '/app-insights'
    | '/app-metas'
    | '/app-patrimonio'
    | '/app-planejamento'
    | '/app-relatorios'
    | '/app-transacoes'
    | '/cadastro'
    | '/login'
    | '/nova-senha'
    | '/onboarding'
    | '/precos'
    | '/recuperar-senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppChecklistsRoute: typeof AppChecklistsRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContasRoute: typeof AppContasRoute
  AppDividasRoute: typeof AppDividasRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMetasRoute: typeof AppMetasRoute
  AppPatrimonioRoute: typeof AppPatrimonioRoute
  AppPlanejamentoRoute: typeof AppPlanejamentoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  OnboardingRoute: typeof OnboardingRoute
  PrecosRoute: typeof PrecosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-assinatura': {
      id: '/app-assinatura'
      path: '/app-assinatura'
      fullPath: '/app-assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-checklists': {
      id: '/app-checklists'
      path: '/app-checklists'
      fullPath: '/app-checklists'
      preLoaderRoute: typeof AppChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-configuracoes': {
      id: '/app-configuracoes'
      path: '/app-configuracoes'
      fullPath: '/app-configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-contas': {
      id: '/app-contas'
      path: '/app-contas'
      fullPath: '/app-contas'
      preLoaderRoute: typeof AppContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-dividas': {
      id: '/app-dividas'
      path: '/app-dividas'
      fullPath: '/app-dividas'
      preLoaderRoute: typeof AppDividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-insights': {
      id: '/app-insights'
      path: '/app-insights'
      fullPath: '/app-insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-metas': {
      id: '/app-metas'
      path: '/app-metas'
      fullPath: '/app-metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-patrimonio': {
      id: '/app-patrimonio'
      path: '/app-patrimonio'
      fullPath: '/app-patrimonio'
      preLoaderRoute: typeof AppPatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-planejamento': {
      id: '/app-planejamento'
      path: '/app-planejamento'
      fullPath: '/app-planejamento'
      preLoaderRoute: typeof AppPlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-relatorios': {
      id: '/app-relatorios'
      path: '/app-relatorios'
      fullPath: '/app-relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-transacoes': {
      id: '/app-transacoes'
      path: '/app-transacoes'
      fullPath: '/app-transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppChecklistsRoute: AppChecklistsRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContasRoute: AppContasRoute,
  AppDividasRoute: AppDividasRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMetasRoute: AppMetasRoute,
  AppPatrimonioRoute: AppPatrimonioRoute,
  AppPlanejamentoRoute: AppPlanejamentoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTransacoesRoute: AppTransacoesRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  OnboardingRoute: OnboardingRoute,
  PrecosRoute: PrecosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
